blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
]

robert/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'glossary/', views.glossary, name='glossary'),
    url(r'borrowers/', views.borrowers, name='borrowers'),
    url(r'realtors/', views.realtors, name='realtors'),
    url(r'contact/', views.contact, name='contact'),
    url(r'^blog/', include('blog.urls')),
    url(r'^$', views.index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts', on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    photo = models.ImageField(upload_to='post', default='')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])

robert/forms.py
from django import forms

class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True, widget=forms.TextInput(
        attrs = { 'class': 'form-control', 'placeholder': 'John Smith' }))
    contact_email = forms.EmailField(required=True, widget=forms.TextInput(
        attrs = { 'class': 'form-control', 'placeholder': 'johnsmith@gmail.com'}))
    contact_subject = forms.CharField(required=False, widget=forms.TextInput(
        attrs = { 'class': 'form-control', 'placeholder': 'Loan Interest Rate Inquiry'}))
    content = forms.CharField(
            required=False,
            widget=forms.Textarea(
                attrs = { 'class': 'form-control',
                          'placeholder': 'I am interested in seeing what my current interest rate would be for a thirty year fixed rate loan and an adjustable rate loan based on my credit score.'}))

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def post_list(request):
    posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})

robert/views.py
from django.shortcuts import render
from .forms import ContactForm

def index(request):
    return render(request, 'index.html')

def glossary(request):
    return render(request, 'glossary.html')

def realtors(request):
    form_class = ContactForm
    return render(request, 'realtors.html', {'form': form_class})

def borrowers(request):
    form_class = ContactForm
    return render(request, 'borrowers.html', {'form': form_class})

def contact(request):
    form_class = ContactForm
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name', '')
            contact_business_name = request.POST.get('contact_business_name', '')
            contact_email = request.POST.get('contact_email', '')
            contact_telephone = request.POST.get('contact_telephone', '')
            form_content = request.POST.get('content', '')

            template = get_template('contact_template.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_business_name': contact_business_name,
                'contact_email': contact_email,
                'contact_telephone': contact_telephone,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "New contact form submission",
                content,
                "Your website" +'',
                ['scottabrown89@gmail.com'],
                headers = {'Reply-To': contact_email }
            )

            email.send()
            return redirect('index')
    return render(request, 'contact.html', {'form': form_class,})

templates/base.html
<!DOCTYPE html>

<html lang="en">
    {% include "head.html" %}
<body class="clear_top">
    <header>
        {% include "nav.html" %}

        {% block header_content %}
        {% endblock %}
    </header>
        {% block content %}
        {% endblock %}

        {% include 'footer.html' %}
    </body>
        {% include 'js.html' %}
</html>

templates/blog/post/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row blog-detail">
        <h3>{{ post.title }}</h3>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        <img src="{{ post.photo.url }}" width="400" height="400">
        <p class="blog-body">{{ post.body|linebreaks }}
    </div>


</div>
{% endblock %}

templates/blog/post/list.html
{% extends 'base.html' %}

{% block content %}

<div class="container-fluid">

    <h1>Recent News</h1>
    <div class="row" id="blog-row">
    </div>
    {% for post in posts %}
        <div class="row blog-list">
            <div class="col-md-2">
                <img src="{{ post.photo.url }}" width="200" height="150">
            </div>
            <div class="col-md-6">
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
                {{ post.body|truncatewords:30|linebreaks }}
            </div>
        </div>
    {% endfor %}

</div>

{% endblock %}

templates/borrowers.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="container borrowers">
        <img class="img-responsive" id="borrowers-img" src="http://www.supremesouth.com/wp-content/uploads/2014/02/peach2.png">
        <div class="text-borrowers-img">
            <h3 class="borrowers-text">BORROWERS</h3>
            <p class="why-us">Why They Choose Us</p>
            <p class="vision">Our Vision...</p>
            <p class="best">To Become The Best</p>
            <p class="best">Customer Service Company In The</p>
            <p class="best">Mortgage Banking Industry</p>
        </div>
    </div>

    <div class="container-fluid">
        <p class="text-center borrowers">WHY <span class="red">CHOOSE</span> US?</p>
        <div class="row borrowers-text">
            <div class="col-md-12">
                <div class="row" id="box-line">
                </div>
                <div class="row" id="box-line">
                </div>
                <p class="borrowers">Our highly experienced Customer Service Specialists (Processors), Underwriters and Closers are 100% committed to delivering the very best client experience possible.  We do everything in-house, so we’re in control throughout the entire loan process.</br></br>
                Our professional Loan Officers will customize the right loan solution to meet your needs and with your best interest at heart.  We will communicate with you throughout the process so that you feel comfortable each step of the way with no surprises, and we will be ready to close when you are.  We always measure our success by our clients’ willingness to confidently recommend us.</br></br>
    As a matter of fact, our customer satisfaction rate as measured by surveys at closing is over 96%!</p>
                <div class="row" id="box-line">
                </div>
                <div class="row" id="box-line">
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row borrowers-text">
            <div class="row">
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-home" aria-hidden="true"></span><span class="glyph-text">Products</span>
                    <p class="box-glyph-text">We have a full line of loan products to meet your needs, whether it's your first home, second home on the beach , or investment home.</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="glyph-text">Process</span>
                    <p class="box-glyph-text">We have engineered our process to assure we meet your closing date and time, and strive to fund your loan within an hour of commencement of closing.</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span><span class="glyph-text">Associate Sat</span>
                    <p class="box-glyph-text">Happy associates equal happy customers! See why we were named #1 on the 2014 Top Workplace list by the Atlanta Journal Constitution.</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span><span class="glyph-text">Calculator</span>
                    <p class="box-glyph-text">See what your payments might look like with our interactive calculator.</p>
                </div>
            </div>
        </div>
        {% include "contact.html" %}
    </div>
</div>
{% endblock %}

templates/contact.html
<div class="container-fluid">
    <div class="container-fluid">
        <div class="row borrowers-text">
            <p class="borrowers-contact-text"><span class="red">QUESTIONS?</span> PLEASE CONTACT US BELOW:</p>
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="col-form-label">Full Name</label>
                            {{ form.contact_name }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="col-form-label">Email</label>
                            {{ form.contact_email }}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label class="col-form-label">Subject</label>
                            {{ form.contact_subject }}
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-form-label">Message</label>
                    {{ form.content }}
                </div>
                <button class="btn btn-primary">Submit</button>
                <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
            </form>
        </div>
    </div>
</div>

templates/footer.html
<br>
<div class="container-fluid footer">
    <div class="row" id="footer">
    </div>
    </br>
        <div class="text-center">
            <p class="footer">Atlanta Mortgage team. Footer text</p>
        </div>
    </br>
    </div>
</div>

templates/head.html
{% load staticfiles %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Atlanta Mortgage Team</title>
	<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <img class="img-responsive" src="http://www.supremesouth.com/wp-content/uploads/2014/01/SupremeBeachChairiStockChair3_940x434.png">
    <p class="text-center"><span class="red">HOW</span> CAN WE HELP?</p>
    <div class="container-fluid">
        <div class="index-page-boxes">
            <div class="row" id="box-line">
            </div>
            <div class="row" id="box-line">
            </div>
            </br>
            <div class="row">
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-piggy-bank" aria-hidden="true"></span><span class="glyph-text">Borrowers</span>
                    <p class="box-glyph-text">Are you Buying a Home or Need to Refinance? We do this with Speed, Experience & Integrity.</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="glyph-text">Realtors</span>
                    <p class="box-glyph-text">Looking for a Mortgage Partner that Truly Cares About Customer Service & Delivers Consistently?</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span><span class="glyph-text">Builders</span>
                    <p class="box-glyph-text">Close on Time, Fund on Time. No Surprises with Constant Communication? Sound Like a Match?</p>
                </div>
                <div class="col-md-3">
                    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span><span class="glyph-text">Join the Team</span>
                    <p class="box-glyph-text">Searching for a Company that Provides the Highest Level of Service in a Family-Like Environment?</p>
                </div>
            </div>
            </br>
            <div class="row" id="box-line">
            </div>
            <div class="row" id="box-line">
            </div>
        </div> <!-- Index Page Boxes -->
    </div> <!-- Container for Boxes -->
    <p class="text-center"><span class="red" id="index-bottom-text">ABOUT SUPREME LENDING</span><span id="index-bottom-text-smaller">  SOUTHEAST REGION</span></p>
    <a href="https://vimeo.com/183834623?width=800&height=500" id="index-video-img-link"><img class="img-responsive" id="index-video-img" src="http://www.supremesouth.com/wp-content/uploads/2014/04/Thumbnail2.png" width="270" height="180"></a>
</div>
</br>
</br>
{% endblock %}

templates/js.html
{% load staticfiles %}

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/nav.html
<nav class="navbar">
    <div class="container-fluid">
        <div class="collapse navbar-collapse">
            <div class="navbar-header">
                <a href="{% url 'index' %}"><img class="img-responsive" src="http://www.supremesouth.com/wp-content/uploads/2013/09/Supreme-Lending-2008-Stacked-e1388260116333.jpg"></a>
			</div>
            <ul class="nav navbar-nav">
                <li><a href="{% url 'borrowers' %}">BORROWERS</a></li>
                <li><a href="{% url 'realtors' %}">REALTORS</a></li>
                <li><a href="#">BUILDERS</a></li>
                <li><a href="#">BLANK</a></li>
                <li><a href="#">ABOUT US</a></li>
                <li><a href="{% url 'glossary' %}">GLOSSARY</a></li>
                <li><a href="{% url 'blog:post_list' %}">BLOG</a></li>
            </ul>
        </div>
        <div class="row" id="nav-border-bottom">
        </div>
    </div>
</nav>

templates/realtors.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="container borrowers">
        <img class="img-responsive" id="realtors-img" src="http://www.supremesouth.com/wp-content/uploads/2014/02/RoadHome2.png">
        <div class="text-borrowers-img">
            <h3 class="borrowers-text">REALTORS</h3>
            <p class="why-us">Why They Choose Us</p>
            <p class="vision">Our Vision...</p>
            <p class="best">To Become The Best</p>
            <p class="best">Customer Service Company In The</p>
            <p class="best">Mortgage Banking Industry</p>
        </div>
    </div>

    <div class="container-fluid">
        <p class="text-center borrowers"><span class="red">WHY REALTORS</span> LOVE US</p>
        <div class="row borrowers-text">
            <div class="col-md-12">
                <div class="row" id="box-line">
                </div>
                <div class="row" id="box-line">
                </div>
                <ul>
                    <li class="realtors">Speed - We can close a loan in as little as 8 days</li>
                    <li class="realtors">Flexibility & Control - We do all our processing, underwriting & closing/funding in-house</li>
                    <li class="realtors">Close on time (defined as closing on the scheduled date)</li>
                    <li class="realtors">Fund on time (defined as checks cut at closing within one hour of starting)</li>
                    <li class="realtors">Peace of Mind - Borrowers can receive a Commitment Letter within 3 days of file receipt by our processing team</li>
                    <li class="realtors">Wide Range of Products to help your Customer Qualify</li>
                    <li class="realtors">You're Kept in the Loop - Loan status communicated to you throughout the loan process</li>
                </ul>
                <div class="row" id="box-line">
                </div>
                <div class="row" id="box-line">
                </div>
            </div>
        </div>
    </div>
    {% include "contact.html" %}
</div>
{% endblock %}